### ISSUE TITLE
Reboot warning…

### ISSUE THREAD

**Issue by ChristopherA** [thisaaronm/macOS_softwareUpdate#1]
Since this is an interactive script, it would probably be best to stop once completed and warn the user before rebooting, in case they are doing some other activity.

**Comment by thisaaronm** [comment]
More explanation in [issue #2 ](https://github.com/thisaaronm/macOS_softwareUpdate/issues/2), but instead of stopping, I'll be adding a prompt, asking the user to, when they're ready, press any key to reboot, or to break out of the script if they do not want to reboot.
